### ISSUE TITLE
学长，thudml这个包下载不了啊

### ISSUE THREAD

**Issue by Breeze-Zero** [zbr17/DRML#1]

**Comment by zbr17** [comment]
抱歉，由于最近thudml进行了一次版本更新，目前版本号为v0.1.1，请使用pip下载v0.1.1版本，目前已对requirement.txt进行了修正，谢谢！

**Comment by zbr17** [comment]
Hello！thudml包目前更名为gedml，相关依赖的安装信息已进一步更新！
