### ISSUE TITLE
[Fail Examples] Can I see the fail examples? 

### ISSUE THREAD

**Issue by Sunjuhyeong** [zbr17/DRML#2]
Hi! Thanks for your interesting works.

I am a beginner in the field of Deep Metal Learning.

From the code, Recall@1 is calculated. I would like to ask how to see images fail to be recalled ( fail examples in Recall@1). That is, when the DRML model searches for an image, I want to see images that have not been successfully searched. Which file should I write this code from?

Once again, I'm a very beginner. The scale of this code feels large, and it is difficult to grasp the structure. If you answer, it will be of great help. Thank you.

**Comment by zbr17** [comment]
Hi! This repo is extended based on another repo [GeDML](https://github.com/zbr17/GeDML).  
And the evaluation code is in the path: [GeDML/src/gedml/core/evaluators](https://github.com/zbr17/GeDML/tree/master/src/gedml/core/evaluators). :blush:

**Comment by Sunjuhyeong** [comment]
Thank you for your answer!
